

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/teams_collaboration_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Manoron2021@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================================
# EMAIL CONFIGURATION (GMAIL)
# ================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=snopitech@gmail.com
spring.mail.password=vrnu dpit gqwf pvmq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.frontend.url=http://localhost:5173

spring.jpa.open-in-view=false
logging.level.com.snopitech.teams_collaboration_backend=DEBUG